### ISSUE TITLE
Part C. Create hyperlinks.

### ISSUE THREAD

**Issue by AlexZhidkov** [LegalX/PartWays#24]
When section of the Act are mentioned in the text create hyperlinks to allow user to go directly to that legal document. Links: 
section 61 - http://www.austlii.edu.au/au/legis/cth/consol_act/fla1975114/s61da.html
subsection 79 - http://www.austlii.edu.au/cgi-bin/sinodisp/au/legis/cth/consol_act/fla1975114/s79.html
subsection 90SM - http://www.austlii.edu.au/au/legis/cth/consol_act/fla1975114/s90sm.html
section 90MZA - http://www.austlii.edu.au/cgi-bin/sinodisp/au/legis/cth/consol_act/fla1975114/s90mza.html

**Comment by AlexZhidkov** [comment]
Please test

**Comment by OxanaMorozova** [comment]
Tested. All good.

**Comment by OxanaMorozova** [comment]
Test time 10 min.
