### ISSUE TITLE
Develop Part H. Details for property or maintenance orders

### ISSUE THREAD

**Issue by AlexZhidkov** [LegalX/PartWays#28]
Develop form for entering data for "Part H. Details for property or maintenance orders" of the Application for Consent Orders.
Use [tabs](https://material.angular.io/components/component/tabs) for subsections as Income, Child Support, etc.
Develop HTML, model, component and unit tests. Files location src/app/property.
Form should be dynamic, hiding not relevant inputs according to users choice of answers. 
Parent issue #4.

**Comment by AlexZhidkov** [comment]
Please test.

**Comment by OxanaMorozova** [comment]
Items 37-49 are tested

**Comment by OxanaMorozova** [comment]
Items 50-71 are tested.
