### ISSUE TITLE
Develop Part I Effect of property orders sought

### ISSUE THREAD

**Issue by AlexZhidkov** [LegalX/PartWays#29]
Develop form for entering data for "Part I Effect of property orders sought" of the Application for Consent Orders.
Develop HTML, model, component and unit tests. Files location src/app/property.
Form should be responsive and usable on mobile devices.
Parent issue #4.

**Comment by AlexZhidkov** [comment]
Please test at https://partways-dev.firebaseapp.com/Property

**Comment by OxanaMorozova** [comment]
All good. UI needs improvement on mobile screen.
