### ISSUE TITLE
User feedback system

### ISSUE THREAD

**Issue by AlexZhidkov** [LegalX/PartWays#31]
Research and implement system to allow users provide feedback and log problems with app.

**Comment by AlexZhidkov** [comment]
https://www.helpshift.com

**Comment by AlexZhidkov** [comment]
@OxanaMorozova  Please test user feedback feature. You can open it up by clicking this icon:
![capture](https://cloud.githubusercontent.com/assets/8213739/24578855/762d27a0-171c-11e7-971d-ada37d8e8513.PNG)

**Comment by OxanaMorozova** [comment]
Tested
