### ISSUE TITLE
Change icon to partways.ico

### ISSUE THREAD

**Issue by twiteli** [LegalX/PartWays#40]
1) PNG icon file
![partways_icon1](https://cloud.githubusercontent.com/assets/7564907/24250404/c0a2e8ea-1011-11e7-92b0-5cfdfdfbcc32.png)
2) convert to ICO http://convertico.com/
3) Replace Angular ico with file

**Comment by AlexZhidkov** [comment]
You might need to refresh your browser to clear cache and force it to update app to the new version.
