### ISSUE TITLE
Part C: a big chunk of data is impossible to fill

### ISSUE THREAD

**Issue by TAbdiukov** [LegalX/PartWays#56]
UPDATE: My fault, I got a bit confused with this multi-level system, not so much is missing. Still though, I cannot find the "Details of the order/agreement/parenting plan/undertaking" field. See the screenshots
![2](https://cloud.githubusercontent.com/assets/18607514/24442997/5f4f986e-1493-11e7-800e-ccaeca92a1f4.JPG)
![1](https://cloud.githubusercontent.com/assets/18607514/24442998/5f555092-1493-11e7-81a5-6b065202ecde.JPG)

**Comment by OxanaMorozova** [comment]
All good.
