### ISSUE TITLE
Part C: Some fields display incorrect data

### ISSUE THREAD

**Issue by TAbdiukov** [LegalX/PartWays#57]
See the screenshot. 
Some fields display the incorrect data on the printing page. I did not enter the same data on these fields.

![capture](https://cloud.githubusercontent.com/assets/18607514/24441768/c8c2f1fc-148d-11e7-9035-34b835d38b23.JPG)

**Comment by AlexZhidkov** [comment]
Problem is names of inputs should be unique. 
![capture](https://cloud.githubusercontent.com/assets/8213739/24460933/4fb94c3a-14d2-11e7-9c6b-d6485e52365b.PNG)

**Comment by OxanaMorozova** [comment]
Can not reproduce.
