### ISSUE TITLE
Part A About the parties

### ISSUE THREAD

**Issue by AlexZhidkov** [LegalX/PartWays#77]
Please test.

**Comment by OxanaMorozova** [comment]
All  good. Item 3 and 5 have some explanations which are not included in to the form. Should they be visible?
![part a item 3](https://cloud.githubusercontent.com/assets/26598190/24587425/c63be7be-17e8-11e7-8fd0-72b31b8286eb.PNG)
![part a item 5](https://cloud.githubusercontent.com/assets/26598190/24587426/c659385a-17e8-11e7-97aa-bba924326c59.PNG)

**Comment by twiteli** [comment]
Not necessary for MVP
Add as issues for next version once we have hover text active for instructions
